version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
  django:
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: node
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
