# Generated by Django 2.2 on 2020-10-18 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='author_name',
            field=models.CharField(default='Arthur Dent', max_length=100, verbose_name='Author Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Author Name'),
            preserve_default=False,
        ),
    ]
